
## Regression Models: Course Project

# Does the type of transmission affects the fuel consumption?

#### Sagi Greenstine

## Executive Summary

This report is based on the ```mtcars``` dataset data and refers to two following questions:  
1. Is an automatic or manual transmission better for MPG?  
2. Quantify the MPG difference between automatic and manual transmissions.  

Brief. 
Roughly the equivalent of 2 pages or less for the main text. 
Supporting figures in an appendix can be included up to 5 total pages including the 2 for the main report. 
The appendix can only include figures.
Include a first paragraph executive summary.

Did the student interpret the coefficients correctly?
Did the student do some exploratory data analyses?
Did the student fit multiple models and detail their strategy for model selection?
Did the student answer the questions of interest or detail why the question(s) is (are) not answerable?
Did the student do a residual plot and some diagnostics?
Did the student quantify the uncertainty in their conclusions and/or perform an inference correctly?

## Data Analysis

Please see the exploratory analysis of the dataset in Appendix.

### Method

### The ```mtcars``` Dataset

The data was extracted from the 1974 Motor Trend US magazine, and comprises fuel consumption and 10 aspects of automobile design and performance for 32 automobiles (1973–74 models).
Source: Henderson and Velleman (1981), Building multiple regression models interactively. Biometrics, 37, 391–411.

* Simple Linear Regression - lm(mpg ~ am, data = mtcars)
* Multiple Regression - lm(mpg ~ wt + qsec + am, data=mtcars)

### Results

## Conclusions

## Appendix

### Exploratory Data Analysis

A data frame with 32 observations on 11 variables.  

[, 1]	mpg	Miles/(US) gallon  
[, 2]	cyl	Number of cylinders  
[, 3]	disp	Displacement (cu.in.)  
[, 4]	hp	Gross horsepower  
[, 5]	drat	Rear axle ratio  
[, 6]	wt	Weight (lb/1000)  
[, 7]	qsec	1/4 mile time  
[, 8]	vs	V/S  
[, 9]	am	Transmission (0 = automatic, 1 = manual)  
[,10]	gear	Number of forward gears  
[,11]	carb	Number of carburetors  
